# Pipeline configuration for end-to-end data processing
# This orchestrates the complete workflow: merge -> clean -> aggregate -> clean

# Pipeline metadata
pipeline:
  name: "Forex Data Processing Pipeline"
  description: "Process raw tick data through merge, clean, aggregate, and final clean steps"
  version: "1.0"

# Steps to execute in order (available: merge, clean_ticks, aggregate, split, winsorize, clean_aggregated, featurize, clean_featurized, visualize)
# steps: [merge, clean_ticks, aggregate, split, winsorize, clean_aggregated, featurize, clean_featurized, visualize]
steps: [split, winsorize, clean_aggregated, featurize, clean_featurized, visualize]
# steps: [merge, clean_ticks, aggregate, split, winsorize, clean_aggregated, featurize, clean_featurized, visualize]

# Global output directory for all stages
output_directory: data

# Step 1: Merge Configuration
merge:
  # List of symbols and their corresponding folder paths to process
  symbols:
    - symbol: audusd
      folder_path: data/raw-tick-data/raw data/audusd
    - symbol: eurusd
      folder_path: data/raw-tick-data/raw data/eurusd
    # - symbol: gbpusd
    #   folder_path: data/raw-tick-data/raw data/gbpusd
    # - symbol: usdjpy
    #   folder_path: data/raw-tick-data/raw data/usdjpy
    # - symbol: usdcad
    #   folder_path: data/raw-tick-data/raw data/usdcad
    # - symbol: usdchf
    #   folder_path: data/raw-tick-data/raw data/usdchf
    # - symbol: nzdusd
    #   folder_path: data/raw-tick-data/raw data/nzdusd
    # - symbol: dowjones
    #   folder_path: data/raw-tick-data/raw instruments/dowjones
    # - symbol: ftse100
    #   folder_path: data/raw-tick-data/raw instruments/ftse100
    # - symbol: xauusd
    #   folder_path: data/raw-tick-data/raw instruments/xauusd

# Step 2: First Clean Configuration (for tick data)
clean_ticks:
  time_column: timestamp

# Step 3: Aggregate Configuration
aggregate:
  time_window: 1H  # Options: 30S, 1min, 5min, 15min, 30min, 1H, 4H, 1D, 1W
  output_filename: forex_data
  aggregators:
    - tick_count
    - open
    - high
    - low
    - close
    - mean
    - spread
    - volume
    - volatility
    - vwap
    - ofi

# Step 4: Split Configuration
split:
  train: 0.6
  val: 0.2
  test: 0.2

# Step 5: Winsorization Configuration
winsorize:
  - aggregations: [tick_count, spread, volatility, volume]
    high: 0.99
    low: 0.0

# Step 6: Final Clean Configuration (for aggregated data)
clean_aggregated:

# Step 7: Featurize Configuration
featurize:
  output_filename: forex_data
  featurizers:
    log_pct_change:

# Step 8: Final Clean Configuration (for featurized data)
clean_featurized:

# Step 9: Visualization Configuration
visualize:
  split:
    train: 0.7
    val: 0.15
    test: 0.15
