name: CI

on:
  push:
    branches: [ main, develop, prep/copilot-review ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    name: Lint and Format Check
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black ruff isort
    
    - name: Check formatting with black
      run: black --check src/ tests/ scripts/
    
    - name: Check imports with isort
      run: isort --check-only --profile black src/ tests/ scripts/
    
    - name: Lint with ruff
      run: ruff check src/ tests/ scripts/

  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
        pip install pandas-stubs types-PyYAML
    
    - name: Type check with mypy
      run: mypy src/atlasfx --ignore-missing-imports --no-strict-optional
      continue-on-error: true  # Don't fail CI on type errors yet

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    needs: [lint]  # Run tests only if linting passes
    
    strategy:
      matrix:
        python-version: ["3.12", "3.11", "3.10"]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    
    - name: Run tests with coverage
      run: |
        pytest tests/ -v --cov=src/atlasfx --cov-report=xml --cov-report=term-missing --cov-fail-under=10
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      if: matrix.python-version == '3.10'
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
        verbose: true

  validate-schema:
    name: Validate Data Schema
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    
    - name: Validate schema and test fixtures
      run: |
        python -m atlasfx.data.validators --sample tests/fixtures/sample_tick_data.csv --type tick_data
